force-app/main/default/objects/Billing_Rule__c/Billing_Rule__c.object-meta.xml
<CustomObject>
    <label>Billing Rule</label>
    <nameField>
        <label>Billing Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Rule__c/fields/Non_billable__c.field-meta.xml
<CustomField>
    <fullName>Non_billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non-billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Rule__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Billing_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Contacts</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Billing_Rule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Rule</label>
    <referenceTo>Billing_Rule__c</referenceTo>
    <relationshipLabel>Billing Rules</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consultants</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TaskServices.cls
public with sharing class TaskServices {

    public static List<Contact> getConsultants() {
        List<Id> consultantIds = new List<Id>();
        List<Project__c> projects = [SELECT Primary_Contact__c FROM Project__c WHERE Primary_Contact__c != null];
        
        for (Project__c project : projects) {
            consultantIds.add(project.Primary_Contact__c);
        }
        List<Contact> allConsultants = [SELECT Name FROM Contact WHERE Id IN :consultantIds];
        return allConsultants;
    }

    public static List<Task__c> getTasks(Id consultantId, Date currentWeekDate) {
        Set<Id> selectedTasksId = new Set<Id>();

        List<Time__c> times = [
            SELECT Task__c
            FROM Time__c
            WHERE Date__c >= :currentWeekDate 
                AND Date__c <= :currentWeekDate.addDays(6)
        ];

        for (Time__c workTime : times) {
            selectedTasksId.add(workTime.Task__c);
        }

        List<Task__c> selectedTasks = [
            SELECT Name, 
                (SELECT Time_spend__c, Date__c FROM Times__r), 
                Consultant__r.Name, 
                Project__r.Name, 
                Billing_Rule__r.Non_billable__c  
            FROM Task__c 
            WHERE Consultant__c = :consultantId
                AND ID IN :selectedTasksId];

        return selectedTasks;
    }

    public static List<Date> getWeekDates(Date weekDate) {
        Date currentWeekDate = Date.today().toStartofWeek();
        List<Date> previousWeekDates = new List<Date>{currentWeekDate};
        Integer numberOfpreviousWeeks = 5;

        for (Integer i = 0; i < numberOfpreviousWeeks; i ++) {
            currentWeekDate = currentWeekDate.addDays(-7);
            if (currentWeekDate != weekDate) {
                previousWeekDates.add(currentWeekDate);
            }
        }
        return previousWeekDates;
    }

    public static List<Time__c> getTimesByTask(Date currentWeekDate, Task__c task) {
        Integer numberOfWorkDays = 7;
        List<Time__c> times = [
            SELECT Time_spend__c, Date__c, Task__c, Task__r.Billing_Rule__c, Task__r.Project__c 
            FROM Time__c 
            WHERE Task__c = :task.Id 
                AND Date__c >= :currentWeekDate
                AND Date__c <= :currentWeekDate.addDays(6)
        ];
        Map<Date, Time__c> existedWorkDateToTime = new Map<Date, Time__c>();
        Map<Date, Time__c> allWorkDateToTime = new Map<Date, Time__c>();
        for (Integer i = 0; i < times.size(); i++) {
            existedWorkDateToTime.put(times[i].Date__c, times[i]);
        }
        
        for (Integer i = 0; i < numberOfWorkDays; i++) {
            if (!existedWorkDateToTime.containsKey(currentWeekDate.addDays(i))) {
                Time__c emptyTime = new Time__c(
                        Name=currentWeekDate.addDays(i).format() + ' ' + task.Name,
                        Billing_Rule__c=task.Billing_Rule__c,
                        Task__c=task.Id,
                        Project__c=task.Project__c,
                        Date__c=currentWeekDate.addDays(i),
                        Time_spend__c=0);
                AllWorkDateToTime.put(currentWeekDate.addDays(i), emptyTime);
            }
            else {
                AllWorkDateToTime.put(
                    currentWeekDate.addDays(i), existedWorkDateToTime.get(currentWeekDate.addDays(i))
                );
            }
        }
        return AllWorkDateToTime.values();
    }
}