force-app/main/default/objects/Billing_Rule__c/Billing_Rule__c.object-meta.xml
<CustomObject>
    <label>Billing Rule</label>
    <nameField>
        <label>Billing Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Rule__c/fields/Non_billable__c.field-meta.xml
<CustomField>
    <fullName>Non_billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non-billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Rule__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Billing_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Billing_Rule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Rule</label>
    <referenceTo>Billing_Rule__c</referenceTo>
    <relationshipLabel>Billing Rules</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consultants</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TaskController.cls
public class TaskController {
    public List<SelectOption> consultantLst {get;set;}
    public String selectedConsultant {get;set;}
    @AuraEnabled
    public static List<Task__c> getTasks() {
        List<Task__c> selectedTasks = [SELECT Name, Consultant__r.Name, Project__r.Name, Billing_Rule__r.Non_billable__c  FROM Task__c WHERE Consultant__c != null];
        return selectedTasks;
    }
    
    public static Set<Id> getTaskIds() {
        Set<Id> taskIds = new Set<Id>();
        List<Task__c> selectedTasks = [SELECT Id  FROM Task__c WHERE Consultant__c != null];
        for (Task__c task : selectedTasks) {
            taskIds.add(task.Id);
        }
        return taskIds;
    }
    
    @AuraEnabled
    public static List<Task__c> getNeededTasks(Consultant__c consultant) {
        List<Task__c> selectedTasks = [
            SELECT Name, Consultant__r.Name, Project__r.Name, Billing_Rule__r.Non_billable__c 
            FROM Task__c
            WHERE Consultant__c = :consultant.Id
       ];
        return selectedTasks;
    }

    
    @AuraEnabled
    public static List<Consultant__c> getConsultants() {
        Set<Id> consultantIds = new Set<Id>();
        for (Task__c task : getTasks()) {
            consultantIds.add(task.Consultant__c);
        }
        List<Consultant__c> options = [SELECT Name FROM Consultant__c WHERE Id IN :consultantIds];
       
        return options;
    }
    
    @AuraEnabled
    public static List<Time__c> getTimes(List<Task__c> tasks) {
        
        List<Time__c> selectedTimes = [SELECT Time_spend__c, Date__c, Task__c FROM Time__c WHERE Task__c IN :tasks];
        return selectedTimes;
        
    }
    
    // public void getTasksforConsultant() {
        // List<Task__c> tasksForConsultant = new List<Task__c>();
        // for (Task__c task : getTasks()) {
            // if (task.Consultant__c == selectedConsultant.Id) {
                // tasksForConsultant.add(task);
            // }
        // }
    // }
    
    public List<Time__c> getTime() {
		List<Project__c> projects = [SELECT Id FROM Project__c];        
        List<Time__c> times = [SELECT Name, Time_spend__c FROM Time__c WHERE Task__c IN :getTasks()];
        return times;
    }

}